"""build_allowlist.py — regenerate app/known_customers.py from the customer master.

    python tools/build_allowlist.py "path/to/Customer_Contact.xlsx"

Re-run this whenever the customer list changes. It reads the workbook, cleans
and de-duplicates the emails and mobiles, works out which domains are safe to
match wholesale (corporate) versus which must be matched per-address (free
providers like gmail), and rewrites app/known_customers.py.

Expected columns (case/space-insensitive): an e-mail column and a mobile
column. Others are ignored.
"""
from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

import pandas as pd

INTERNAL = {"bharatsteels.in", "metfraa.com", "crayonroofings.com", "vestrics.in"}
FREE = {
    "gmail.com", "yahoo.com", "yahoo.co.in", "yahoo.in", "hotmail.com",
    "outlook.com", "rediffmail.com", "ymail.com", "live.com", "icloud.com",
    "aol.com", "protonmail.com", "msn.com",
}
TYPO_FIX = {"gamil.com": "gmail.com", "gmial.com": "gmail.com", "gmai.com": "gmail.com"}

EMAIL_RE = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")
DOMAIN_RE = re.compile(r"[a-z0-9.-]+\.[a-z]{2,}")


def find_col(df: pd.DataFrame, *needles: str) -> str | None:
    for c in df.columns:
        low = str(c).strip().lower()
        if any(n in low for n in needles):
            return c
    return None


def clean_emails(raw) -> list[str]:
    if pd.isna(raw):
        return []
    out = []
    for part in re.split(r"[;,/\s]+", str(raw).strip().lower()):
        p = part.strip().strip('"').strip("'")
        for bad, good in TYPO_FIX.items():
            if p.endswith(bad):
                p = p[: -len(bad)] + good
        if not EMAIL_RE.fullmatch(p):
            continue
        local, dom = p.split("@", 1)
        if re.fullmatch(r"\d+", local):      # all-numeric local = data noise
            continue
        if dom in INTERNAL:
            continue
        out.append(p)
    return out


def clean_mobiles(raw) -> list[str]:
    if pd.isna(raw):
        return []
    return re.findall(r"[6-9]\d{9}", re.sub(r"\D", " ", str(raw)))


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    src = Path(sys.argv[1])
    if not src.exists():
        print(f"File not found: {src}")
        sys.exit(1)

    df = pd.read_excel(src, header=0)
    df.columns = [str(c).strip() for c in df.columns]

    email_col = find_col(df, "mail", "email", "e-mail")
    mobile_col = find_col(df, "mobile", "phone", "contact")
    if not email_col:
        print("Could not find an e-mail column. Columns:", list(df.columns))
        sys.exit(1)
    print(f"Using email column: {email_col!r}, mobile column: {mobile_col!r}")

    emails: set[str] = set()
    mobiles: set[str] = set()
    for _, row in df.iterrows():
        for e in clean_emails(row.get(email_col)):
            emails.add(e)
        if mobile_col:
            for m in clean_mobiles(row.get(mobile_col)):
                mobiles.add(m)

    dom_counts = Counter(e.split("@")[1] for e in emails)
    corp_domains = {
        d for d in dom_counts
        if d not in FREE and d not in INTERNAL
        and DOMAIN_RE.fullmatch(d) and len(d) > 4
    }

    print(f"Emails: {len(emails)} | Mobiles: {len(mobiles)} | "
          f"Corp domains: {len(corp_domains)} | "
          f"Free-provider addresses matched individually: "
          f"{sum(1 for e in emails if e.split('@')[1] in FREE)}")

    out_path = Path(__file__).resolve().parent.parent / "app" / "known_customers.py"
    with out_path.open("w") as f:
        f.write('"""Known-customer allowlist, generated from the BSC customer master.\n\n')
        f.write("Generated by tools/build_allowlist.py — do not hand-edit; re-run that\n")
        f.write("script against an updated Customer_Contact.xlsx to refresh.\n\n")
        f.write(f"Source: {src.name}  |  {len(emails)} emails, "
                f"{len(mobiles)} mobiles, {len(corp_domains)} domains.\n\n")
        f.write("A mail matching any of these — exact email, exact mobile, or corporate\n")
        f.write("domain — is treated as a known customer and SKIPS the keyword prefilter,\n")
        f.write("going straight to Claude.\n\n")
        f.write("Free providers are matched per-address via KNOWN_EMAILS, never by\n")
        f.write("domain, since most customers use them.\n\"\"\"\n\n")
        f.write("KNOWN_EMAILS = frozenset({\n")
        for e in sorted(emails):
            f.write(f"    {e!r},\n")
        f.write("})\n\n")
        f.write("KNOWN_MOBILES = frozenset({\n")
        for m in sorted(mobiles):
            f.write(f"    {m!r},\n")
        f.write("})\n\n")
        f.write("KNOWN_DOMAINS = frozenset({\n")
        for d in sorted(corp_domains):
            f.write(f"    {d!r},\n")
        f.write("})\n")

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
